//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to count songs..
        /// </summary>
        public static string UnableToCountSongsExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCountSongsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to count tickets..
        /// </summary>
        public static string UnableToCountTicketsExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCountTicketsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to count users..
        /// </summary>
        public static string UnableToCountUsersExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCountUsersExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create song..
        /// </summary>
        public static string UnableToCreateSongExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCreateSongExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create ticket..
        /// </summary>
        public static string UnableToCreateTicketExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCreateTicketExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create user..
        /// </summary>
        public static string UnableToCreateUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCreateUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to delete song..
        /// </summary>
        public static string UnableToDeleteSongExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteSongExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to delete ticket..
        /// </summary>
        public static string UnableToDeleteTicketExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteTicketExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to delete user..
        /// </summary>
        public static string UnableToDeleteUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get access token from Facebook..
        /// </summary>
        public static string UnableToGetFacebookAccessTokenExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetFacebookAccessTokenExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get user information from Facebook..
        /// </summary>
        public static string UnableToGetFacebookUserInfoExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetFacebookUserInfoExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get HTTP-response..
        /// </summary>
        public static string UnableToGetHttpResponseExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetHttpResponseExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get song..
        /// </summary>
        public static string UnableToGetSongExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetSongExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get songs..
        /// </summary>
        public static string UnableToGetSongsExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetSongsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get ticket..
        /// </summary>
        public static string UnableToGetTicketExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetTicketExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get tickets..
        /// </summary>
        public static string UnableToGetTicketsExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetTicketsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get user..
        /// </summary>
        public static string UnableToGetUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get users..
        /// </summary>
        public static string UnableToGetUsersExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetUsersExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get access token from Vkontakte..
        /// </summary>
        public static string UnableToGetVkontakteAccessTokenExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetVkontakteAccessTokenExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get user information from Vkontakte..
        /// </summary>
        public static string UnableToGetVkontakteUserInfoExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetVkontakteUserInfoExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set offline status for user..
        /// </summary>
        public static string UnableToSetUserOfflineExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToSetUserOfflineExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to set online status for user..
        /// </summary>
        public static string UnableToSetUserOnlineExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToSetUserOnlineExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to update song..
        /// </summary>
        public static string UnableToUpdateSongExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateSongExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to update ticket..
        /// </summary>
        public static string UnableToUpdateTicketExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateTicketExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to update user..
        /// </summary>
        public static string UnableToUpdateUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateUserExceptionMessage", resourceCulture);
            }
        }
    }
}
