//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add quote.
        /// </summary>
        public static string AddQuoteFormAddQuote {
            get {
                return ResourceManager.GetString("AddQuoteFormAddQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New quote.
        /// </summary>
        public static string AddQuoteFormNewQuote {
            get {
                return ResourceManager.GetString("AddQuoteFormNewQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MMMM d a\t h:mm tt.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на That page you requested does not exist!.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It&apos;s just an internal server error, take it easy!.
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It&apos;s just an unexpected error, take it easy!.
        /// </summary>
        public static string ErrorIndex {
            get {
                return ResourceManager.GetString("ErrorIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oops, something&apos;s wrong :(.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fromsong - Let&apos;s listen to the music!.
        /// </summary>
        public static string FromSongProject {
            get {
                return ResourceManager.GetString("FromSongProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js.
        /// </summary>
        public static string JQuerySource {
            get {
                return ResourceManager.GetString("JQuerySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add ticket.
        /// </summary>
        public static string LayoutAddTicket {
            get {
                return ResourceManager.GetString("LayoutAddTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на by all users.
        /// </summary>
        public static string LayoutByAllUsers {
            get {
                return ResourceManager.GetString("LayoutByAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на it&apos;s very easy.
        /// </summary>
        public static string LayoutItsVeryEasy {
            get {
                return ResourceManager.GetString("LayoutItsVeryEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LayoutLanguage {
            get {
                return ResourceManager.GetString("LayoutLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tickets.
        /// </summary>
        public static string LayoutTickets {
            get {
                return ResourceManager.GetString("LayoutTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Up.
        /// </summary>
        public static string LayoutUp {
            get {
                return ResourceManager.GetString("LayoutUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Share with friends.
        /// </summary>
        public static string ShareBlockTitle {
            get {
                return ResourceManager.GetString("ShareBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin area.
        /// </summary>
        public static string SignInAdminArea {
            get {
                return ResourceManager.GetString("SignInAdminArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string SignInInformation {
            get {
                return ResourceManager.GetString("SignInInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You should login to add quotes..
        /// </summary>
        public static string SignInInformationContent {
            get {
                return ResourceManager.GetString("SignInInformationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login with.
        /// </summary>
        public static string SignInLoginWith {
            get {
                return ResourceManager.GetString("SignInLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string SignInLogout {
            get {
                return ResourceManager.GetString("SignInLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My quotes.
        /// </summary>
        public static string SignInMyQuotes {
            get {
                return ResourceManager.GetString("SignInMyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на or.
        /// </summary>
        public static string SignInOr {
            get {
                return ResourceManager.GetString("SignInOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login using your profile.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VKontakte.
        /// </summary>
        public static string SignInVkontakte {
            get {
                return ResourceManager.GetString("SignInVkontakte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New quote.
        /// </summary>
        public static string SongAddTitle {
            get {
                return ResourceManager.GetString("SongAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s do it now!.
        /// </summary>
        public static string SongByCurrentUserEmptyDescription {
            get {
                return ResourceManager.GetString("SongByCurrentUserEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You didn&apos;t add any quotes.
        /// </summary>
        public static string SongByCurrentUserEmptySubject {
            get {
                return ResourceManager.GetString("SongByCurrentUserEmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coming soon, we hope!.
        /// </summary>
        public static string SongByUserEmptyDescription {
            get {
                return ResourceManager.GetString("SongByUserEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no quotes by this user yet.
        /// </summary>
        public static string SongByUserEmptySubject {
            get {
                return ResourceManager.GetString("SongByUserEmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quotes by user.
        /// </summary>
        public static string SongByUserTitle {
            get {
                return ResourceManager.GetString("SongByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на But they will be here very soon!.
        /// </summary>
        public static string SongIndexEmptyDescription {
            get {
                return ResourceManager.GetString("SongIndexEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no quotes by Fromsong project yet.
        /// </summary>
        public static string SongIndexEmptySubject {
            get {
                return ResourceManager.GetString("SongIndexEmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quotes by Fromsong project.
        /// </summary>
        public static string SongIndexTitle {
            get {
                return ResourceManager.GetString("SongIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can add the first one :).
        /// </summary>
        public static string SongListEmptyDescription {
            get {
                return ResourceManager.GetString("SongListEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no quotes yet.
        /// </summary>
        public static string SongListEmptySubject {
            get {
                return ResourceManager.GetString("SongListEmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quotes by all users.
        /// </summary>
        public static string SongListTitle {
            get {
                return ResourceManager.GetString("SongListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My quotes.
        /// </summary>
        public static string SongMyQuotes {
            get {
                return ResourceManager.GetString("SongMyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation.
        /// </summary>
        public static string SongTranslation {
            get {
                return ResourceManager.GetString("SongTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User&apos;s quotes.
        /// </summary>
        public static string SongUserQuotes {
            get {
                return ResourceManager.GetString("SongUserQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The End.
        /// </summary>
        public static string TheEnd {
            get {
                return ResourceManager.GetString("TheEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s do it now!.
        /// </summary>
        public static string TicketByCurrentUserEmptyDescription {
            get {
                return ResourceManager.GetString("TicketByCurrentUserEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You didn&apos;t add any tickets.
        /// </summary>
        public static string TicketByCurrentUserEmptySubject {
            get {
                return ResourceManager.GetString("TicketByCurrentUserEmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coming soon, we hope!.
        /// </summary>
        public static string TicketByUserEmptyDescription {
            get {
                return ResourceManager.GetString("TicketByUserEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no tickets by this user yet.
        /// </summary>
        public static string TicketByUserEmptySubject {
            get {
                return ResourceManager.GetString("TicketByUserEmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tickets by user.
        /// </summary>
        public static string TicketByUserTitle {
            get {
                return ResourceManager.GetString("TicketByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can add the first one :).
        /// </summary>
        public static string TicketListEmptyDescription {
            get {
                return ResourceManager.GetString("TicketListEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no tickets yet.
        /// </summary>
        public static string TicketListEmptySubject {
            get {
                return ResourceManager.GetString("TicketListEmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tickets by all users.
        /// </summary>
        public static string TicketListTitle {
            get {
                return ResourceManager.GetString("TicketListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My tickets.
        /// </summary>
        public static string TicketMyTickets {
            get {
                return ResourceManager.GetString("TicketMyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User&apos;s tickets.
        /// </summary>
        public static string TicketUserTickets {
            get {
                return ResourceManager.GetString("TicketUserTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a\t h:mm tt.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
